version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
      build: .
      ports:
        - "3000:3000"
      volumes:
        - .:/usr/src/docker_projects/flights-cc
      depends_on:
        - db