version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
  web:
      build: .
      ports:
        - "3000:3000"
      volumes:
        - .:/usr/src/docker_projects/flights-cc
      environment:
        DATABASE_HOST: database
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: admin